version: "3"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
    volumes:
      - ./influxdb/data:/var/lib/influxdb

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    links:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  collectd:
    image: vimagick/collectd
    volumes:
      - ./collectd/data:/etc/collectd
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${PORT}:${PORT}"
    restart: always
    links:
      - influxdb
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}

networks:
  default:
    external:
      name: nginx-proxy