version: "3"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "25826:25826"
    env_file:
      - .env.influxdb
    volumes:
      - ./influxdb/data:/var/lib/influxdb

  collectd:
    image: vimagick/collectd
    volumes:
      - ./collectd:/etc/collectd
    links:
      - influxdb
    restart: always
    environment:
      HOST_NAME: server.strangelab.co.uk

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${PORT}:${PORT}"
    restart: always
    links:
      - influxdb
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    env_file:
      - .env.grafana

networks:
  default:
    external:
      name: nginx-proxy