version: "3"

services:
  influxdb:
    image: influxdb:1.0
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
    env_file:
      - .env.influxdb
    volumes:
      - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - ./influxdb/types.db:/usr/share/collectd/types.db:ro

  collectd:
    image: fr3nd/collectd
    privileged: true
    network_mode: host
    volumes:
      - /proc:/mnt/proc:ro
      - ./collectd:/etc/collectd

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${PORT}:${PORT}"
    restart: always
    links:
      - influxdb
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    env_file:
      - .env.grafana
