version: "3"

services:
  collectd:
    image: vimagick/collectd
    volumes:
      - ./collectd/data:/etc/collectd
    pid: host
    net: host
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${PORT}:${PORT}"
    restart: always
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}

networks:
  default:
    external:
      name: nginx-proxy