version: 2
jobs:
  deploy:
    machine:
        enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Deploy
          command: sh ./build/deploy.sh

workflows:
  version: 2
  deploy:
    jobs:
      - deploy