# Uncomment slack and insert your webhook url in order to get notifications on your slack.

receivers:
    - name: 'slack'
      slack_configs:
        - send_resolved: true
          username: 'Prometheus - Alerts'
          channel: '#strange-vps'
          api_url: 'https://hooks.slack.com/services/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'
          text: '{{ .CommonAnnotations.summary }}   --->   {{ .CommonAnnotations.description }}'
